# -*- coding: utf-8 -*-
"""Mini1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178TfA09Q06JJ-B88s5gGyRJfVs-tfD68
"""

import tkinter as tk

items = []  # list to store (product, price, qty)

def add_item():
    product = entry_product.get()
    price = float(entry_price.get())
    qty = int(entry_qty.get())
    items.append((product, price, qty))
    listbox.insert(tk.END, f"{product} x{qty} = ₹{price*qty}")
    entry_product.delete(0, tk.END)
    entry_price.delete(0, tk.END)
    entry_qty.delete(0, tk.END)

def generate_bill():
    total = sum(price*qty for _, price, qty in items)
    output_label.config(text=f"Total Bill: ₹{total:.2f}")

root = tk.Tk()
root.title("🛒 Retail Billing System")
root.geometry("400x400")

tk.Label(root, text="Product:").pack()
entry_product = tk.Entry(root)
entry_product.pack()

tk.Label(root, text="Price:").pack()
entry_price = tk.Entry(root)
entry_price.pack()

tk.Label(root, text="Quantity:").pack()
entry_qty = tk.Entry(root)
entry_qty.pack()

tk.Button(root, text="Add Item", command=add_item, bg="lightblue").pack(pady=5)
listbox = tk.Listbox(root, width=40, height=8)
listbox.pack()

tk.Button(root, text="Generate Bill", command=generate_bill, bg="lightgreen").pack(pady=10)
output_label = tk.Label(root, text="", font=("Arial", 12))
output_label.pack()

root.mainloop()